config/routes.rb
Rails.application.routes.draw do
  resources :codices do
    resources :songs
    resources :practice_sessions, only: [:create, :update]
  end

  resources :practice_session, only: [] do
    resources :practice_session_songs, only: [:show, :create], as: :songs
  end

  resources :instruments

  root 'codices#index'
end

app/models/codex.rb
class Codex < ActiveRecord::Base
  has_many :codex_songs, dependent: :destroy
  has_many :songs, through: :codex_songs
  has_many :practice_sessions

  validates :name, presence: true
end

app/models/codex_song.rb
class CodexSong < ActiveRecord::Base
  belongs_to :codex
  belongs_to :song
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_and_belongs_to_many :practice_sessions

  validates :name, :key, presence: true
end

app/models/practice_session.rb
class PracticeSession < ActiveRecord::Base
  before_validation :assign_instruments, :check_song_presence, on: :create

  has_many :practice_session_songs
  has_many :songs, through: :practice_session_songs
  has_and_belongs_to_many :instruments
  belongs_to :codex

  private

  def assign_instruments
    self.instruments = Instrument.all
    instruments.any?
  end

  def check_song_presence
    codex.songs.any?
  end
end

app/models/practice_session_song.rb
class PracticeSessionSong < ActiveRecord::Base
  before_validation :assign_song, :assign_instrument, on: :create

  belongs_to :practice_session
  belongs_to :song
  belongs_to :instrument

  validates :practice_session_id, :song_id, :instrument_id, presence: true

  private

  def assign_song
    self.song = self.practice_session.codex.songs.sample
    true
  end

  def assign_instrument
    self.instrument = self.practice_session.instruments.sample
    true
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :codex_songs, dependent: :destroy
  has_many :codices, through: :codex_songs

  has_many :practice_session_songs
  has_many :practice_sessions, through: :practice_session_songs

  validates :title, :key, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/codices_controller.rb
class CodicesController < ApplicationController
  before_action :codex, only: [:show, :edit]

  def index
    @codices = Codex.all
    @instruments = Instrument.all
  end

  def new
    @codex = Codex.new
  end

  def create
    if codex.save
      redirect_to @codex, notice: 'Codex Saved'
    else
      flash.now[:error] = 'Codex Not Saved'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if codex.update_attributes(codex_params)
      redirect_to @codex, notice: 'Codex Saved'
    else
      flash.now[:error] = 'Codex Not Saved'
      render :edit
    end
  end

  def destroy
    codex.destroy
    redirect_to codices_path, notice: 'Codex Deleted'
  end

  private

  def codex_params
    params.require(:codex).permit(:name)
  end

  def codex
    @codex ||= params[:id] ? Codex.find(params[:id]) : Codex.new(codex_params)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :instrument, only: [:show, :edit]

  def index
    @instruments = Instrument.all
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    if @instrument.save
      redirect_to @instrument, notice: 'Instrument Saved'
    else
      flash.now[:error] = 'Instrument Not Saved'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if instrument.update_attributes(instrument_params)
      redirect_to instrument, notice: 'Instrument Saved'
    else
      flash.now[:error] = 'Instrument Not Saved'
      render :edit
    end
  end

  def destroy
    instrument.destroy
    redirect_to instruments_url, notice: 'Instrument Deleted'
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :key)
  end

  def instrument
    @instrument = Instrument.find(params[:id])
  end
end

app/controllers/practice_session_songs_controller.rb
class PracticeSessionSongsController < ApplicationController
  before_action :practice_session, :practice_session_song, only: :show

  def create
    @practice_session_song = practice_session.practice_session_songs.build
    practice_session_song.save
    redirect_to practice_session_song_path(practice_session, @practice_session_song)
  end

  def show
  end

  private

  def practice_session
    @practice_session ||= PracticeSession.find(params[:practice_session_id])
  end

  def practice_session_song
    @practice_session_song ||= (
      params[:id] ? PracticeSessionSong.find(params[:id]) : practice_session.practice_session_songs.build
    )
  end
end

app/controllers/practice_sessions_controller.rb
class PracticeSessionsController < ApplicationController
  def create
    if practice_session.save
      @practice_session_song = practice_session.practice_session_songs.create
      redirect_to practice_session_song_path(@practice_session, @practice_session_song), notice: 'Slow Is Faster!'
    else
      flash[:error] = 'Could Not Start Practice Session'
      redirect_to codex
    end
  end

  def update
    practice_session.update_attributes(done: true)
    redirect_to codex, notice: 'Progress, Not Perfection'
  end

  private

  def codex
    @codex ||= Codex.find(params[:codex_id])
  end

  def practice_session
    @practice_session ||= (
      params[:id] ? PracticeSession.find(params[:id]): codex.practice_sessions.build
    )
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :codex, only: [:new, :show, :edit]
  before_action :song, only: [:show, :edit]

  def new
    @song = codex.songs.build
  end

  def create
    if song.save
      song.codex_songs.create(codex: codex, song: song)
      redirect_to codex, notice: "'#{song.title}' Saved To #{codex.name}"
    else
      flash.now[:error] = 'Song Not Saved'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if song.update_attributes(song_params)
      redirect_to codex, notice: 'Song Saved'
    else
      flash.now[:error] = 'Song Not Saved'
      render :edit
    end
  end

  def destroy
    song.destroy
    redirect_to codex, notice: "'#{song.title}' Deleted"
  end

  private

  def song_params
    params.require(:song).permit(:title, :key)
  end

  def codex
    @codex ||= Codex.find(params[:codex_id])
  end

  def song
    @song ||= (
      params[:id] ? Song.find(params[:id]) : codex.songs.build(song_params)
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/codices/_form.html.haml
= form_for @codex do |f|
  = f.label :name
  = f.text_field :name
  = f.submit 'Save'

app/views/codices/edit.html.haml
%h1 Edit Codex

= render 'form'

app/views/codices/index.html.haml
%h1 resonat.io

= link_to 'New Instrument', new_instrument_path
- if @instruments.any?
  %h2 Instruments
  - @instruments.each do |inst|
    %li #{ inst.name} (#{ inst.key })

%hr

= link_to 'New Codex', new_codex_path
- if @codices.any?
  %h2 Codices
  %ul
  - @codices.each do |codex|
    %li= link_to codex.name, codex

app/views/codices/new.html.haml
%h1 New Codex

= render 'form'

app/views/codices/show.html.haml
%h1 #{@codex.name}
= button_to 'Practice', codex_practice_sessions_path(@codex)
= link_to 'Edit Codex', edit_codex_path(@codex)
%hr

%h2 Songs
= link_to 'Add Song', new_codex_song_path(@codex)
- if @codex.songs.any?
  %ul
  - @codex.songs.each do |song|
    %li= link_to "#{ song.title } (#{ song.key })", [@codex, song]

app/views/instruments/_form.html.haml
= form_for @instrument do |f|
  = f.label :name
  = f.text_field :name
  %br
  = f.label :key
  = f.text_field :key
  = f.submit 'Save'

app/views/instruments/edit.html.haml
%h1 Edit Instrument

= render 'form'

app/views/instruments/new.html.haml
%h1 New Instrument

= render 'form'

app/views/instruments/show.html.haml
%h1 #{ @instrument.name }
%h2 Key: #{ @instrument.key }

= link_to 'Edit', edit_instrument_path(@instrument)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }/
    %title Codex
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/practice_session_songs/show.html.haml
%h3 Practicing #{ @practice_session.codex.name }

%hr

%h1 #{ @practice_session_song.song.title }
%h2 in concert #{ @practice_session_song.song.key }
%h2 on #{ @practice_session_song.instrument.name } (#{ @practice_session_song.instrument.key})

%hr

= button_to 'Next', practice_session_songs_path(@practice_session)
= button_to 'Done', codex_practice_session_path(@practice_session.codex, @practice_session), { method: :put }

app/views/songs/_form.html.haml
= form_for [@codex, @song] do |f|
  = f.label :title
  = f.text_field :title
  %br
  = f.label :key
  = f.text_field :key
  %br
  = f.submit 'Save'

app/views/songs/edit.html.haml
%h1 Edit Song

= render 'form'

app/views/songs/new.html.haml
%h1 New Song

= render 'form'

app/views/songs/show.html.haml
%h1 #{ @song.title }
%h2 Key: #{ @song.key }

= link_to 'Edit', edit_codex_song_path(@codex, @song)